(WIP) fixed a bug in extract_features, tryign to figure out what is causing shape issues
   features = features.reshape((features.shape[0], 7 * 7 * 2048))
ValueError: cannot reshape array of size 65536 into shape (32,100352)